# Generated by Django 3.1.4 on 2020-12-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201230_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='croporder',
            name='buyerID',
            field=models.IntegerField(default=0),
        ),
    ]
